version: '3.8'

services:
  backend:
    build:
      context: ../services/server
      dockerfile: ../../docker/backend/Dockerfile.prod
    container_name: transitops-backend-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../services/server/.env
    networks:
      - transitops-network
    restart: always

  frontend:
    build:
      context: ../services/client
      dockerfile: ../../docker/frontend/Dockerfile.prod
    container_name: transitops-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - transitops-network
    restart: always

networks:
  transitops-network:
    driver: bridge
